"""Producer declarations must be explicit and cannot classify drawing names."""
import pytest

from mikrocam.importers.cad_producer import classify_producer, producer_declaration


@pytest.mark.parametrize(('value', 'application'), [
    ('KiCad', 'KiCad'), ('PCBNEW', 'KiCad'), ('Eeschema 9.0', 'KiCad'),
    ('kicad 10.0.6', 'KiCad'), ('Adobe Illustrator 28.0.0 (Windows)', 'Illustrator'),
    ('Illustrator CS6', 'Illustrator'), ('Adobe Illustrator CC 2025', 'Illustrator'),
    ('Inkscape 1.1.1 (3bf5ae0d25, 2021-09-20)', 'Inkscape'),
    ('Labcenter Proteus 8.6', 'Proteus'), ('Proteus 8.6-SP3-Build23669', 'Proteus'),
    ('Adobe Photoshop 28', 'Unknown'), ('KiCadical', 'Unknown'), ('not KiCad', 'Unknown'),
    ('board-Inkscape.svg', 'Unknown'), ('KiCad + Inkscape', 'Unknown'),
    ('Adobe Illustrator 28 (edited by Inkscape)', 'Unknown'), ('', 'Unknown'),
    ('KiCad is merely mentioned', 'Unknown'),
])
def test_bounded_application_names(value, application):
    assert classify_producer(value) == application


@pytest.mark.parametrize('prefix', ['Generator:', 'Creator:', 'Created with ',
                                   'Generated by ', 'Image generated by '])
def test_declared_producer_grammar(prefix):
    assert producer_declaration(f'  {prefix} Inkscape 1.2  ') == 'Inkscape 1.2'


@pytest.mark.parametrize('value', ['Board made for Inkscape', 'KiCad', 'Not generated by KiCad',
                                  'Drawing title: Generator: KiCad', ''])
def test_unstructured_mentions_are_not_declarations(value):
    assert producer_declaration(value) is None


@pytest.mark.parametrize('name', ['a.svg', 'Proteus.svg', 'Inkscape-KiCad.svg'])
def test_dispatcher_uses_exact_bytes_not_name(name):
    import hashlib
    from mikrocam.importers.cad_source import detect_cad_source
    source = b'\xef\xbb\xbf<svg><desc>Image generated by PCBNEW</desc></svg>\r\n'
    record = detect_cad_source(source, name, 'SVG')
    assert record.application == 'KiCad' and record.status == 'identified'
    assert record.source_sha256 == hashlib.sha256(source).hexdigest()
    assert record.source_name == name


@pytest.mark.parametrize(('body', 'status'), [('', 'unknown'),
    ('<desc>Generated by Unsupported CAD</desc>', 'unknown'),
    ('<desc>Generated by Inkscape 1.2</desc><desc>Generated by KiCad</desc>', 'conflicting'),
    ('<desc>Generated by Inkscape 1.2</desc><desc>Generated by Unsupported CAD</desc>', 'conflicting')])
def test_missing_unsupported_or_conflicting_claims_stay_unknown(body, status):
    from mikrocam.importers.cad_source import detect_cad_source
    record = detect_cad_source(f'<svg>{body}</svg>'.encode(), 'KiCad.svg', 'SVG')
    assert record.application == 'Unknown' and record.status == status and record.reason


@pytest.mark.parametrize(('source', 'format'), [(b'<svg', 'SVG'), (b'\xff', 'SVG'),
                                              (b'0\nSECTION\n', 'DXF')])
def test_malformed_source_is_unavailable_with_exact_identity(source, format):
    import hashlib
    from mikrocam.importers.cad_source import detect_cad_source
    record = detect_cad_source(source, 'bad', format)
    assert record.application == 'Unknown' and record.status == 'unavailable'
    assert record.evidence == () and record.source_sha256 == hashlib.sha256(source).hexdigest()


def test_oversized_source_does_not_hash_or_classify_a_prefix(monkeypatch):
    from mikrocam.importers import cad_source
    monkeypatch.setattr(cad_source, 'MAX_CAD_SOURCE_BYTES', 4)
    record = cad_source.detect_cad_source(b'<svg/>', 'x.svg', 'SVG')
    assert record.status == 'unavailable' and record.source_sha256 is None and record.evidence == ()


@pytest.mark.parametrize('args', [('text', 'x.svg', 'SVG'), (b'<svg/>', '', 'SVG'),
                                  (b'<svg/>', 'x.svg', 'svg'), (b'<svg/>', 'x.svg', 'Gerber')])
def test_invalid_caller_contract_raises(args):
    from mikrocam.importers.cad_source import detect_cad_source
    with pytest.raises(ValueError):
        detect_cad_source(*args)


@pytest.mark.parametrize(('format', 'field', 'value', 'application'), [
    ('DXF', 'dxf.999', 'Creator: KiCad', 'Illustrator'),
    ('SVG', 'svg.inkscape.version', '1.2', 'KiCad'),
    ('DXF', 'svg.xmp.CreatorTool', 'KiCad', 'KiCad'),
    ('SVG', 'arbitrary', 'KiCad', 'KiCad'),
    ('SVG', 'svg.desc', 'KiCad', 'KiCad'),
])
def test_stored_claim_cannot_disagree_with_its_retained_evidence(format, field, value, application):
    from mikrocam.core.cad_source import CadSourceAssessment, CadSourceEvidence
    from mikrocam.importers.cad_source import validate_cad_assessment
    record = CadSourceAssessment('x', format, 'a' * 64, application, 'identified',
                                 (CadSourceEvidence(application, field, value),), 'Historical claim')
    with pytest.raises(ValueError):
        validate_cad_assessment(record)
