"""Collapsed plain historical evidence without file or controller access."""
from types import SimpleNamespace
import threading

import pytest
from PyQt6 import QtCore, QtWidgets
from PyQt6.sip import isdeleted

import mikrocam.ui.cad_source as ui
from mikrocam.core.cad_source import CadSourceAssessment, CadSourceEvidence
from mikrocam.core.cad_source_codec import source_to_dict


def assessment(name='<b>source.svg</b>'):
    return CadSourceAssessment(name, 'SVG', 'a' * 64, 'KiCad', 'identified',
                               (CadSourceEvidence('KiCad', 'svg.desc', 'Generated by KiCad 9.0'),),
                               'Explicit declaration; <script>\nKiCad\x00 not authorship.')


@pytest.fixture
def section(qtbot):
    widget = ui.CadSourceSection()
    qtbot.addWidget(widget)
    widget.show()
    return widget


def test_section_collapsed_read_only_literal_evidence(section):
    section.set_assessment(assessment())
    assert not section.toggle.isChecked() and section.details.isHidden()
    assert section.details.isReadOnly()
    assert section.summary_label.textFormat() == QtCore.Qt.TextFormat.PlainText
    section.toggle.click()
    text = section.details.toPlainText()
    assert '<b>source.svg</b>' in text and '<script>\\nKiCad\\x00' in text
    assert 'a' * 64 in text and 'svg.desc' in text
    summary = section.summary_label.text().lower()
    assert 'kicad' in summary and 'identified' in summary
    assert 'historical' in summary and 'authorship' in summary and 'explicit' in summary
    assert not section.findChildren(QtWidgets.QLineEdit)


@pytest.mark.parametrize('replacement', [None, {'fake': True}])
def test_absent_or_wrong_record_clears_previous_details(section, replacement):
    section.set_assessment(assessment('old.svg'))
    section.toggle.click()
    section.set_assessment(replacement)
    assert section.details.toPlainText() == ''
    assert not section.toggle.isEnabled() and not section.toggle.isChecked()
    assert 'old.svg' not in section.summary_label.text()
    assert 'unavailable' in section.summary_label.text().lower()


def test_error_clears_success_and_escapes_bounded_diagnostic(section):
    section.set_assessment(assessment())
    section.set_assessment(assessment(), error='<b>bad</b>\n' + 'x' * 2000)
    assert section.details.toPlainText() == ''
    assert '<b>bad</b>\\n' in section.summary_label.text()
    assert len(section.summary_label.text()) < 1000


def test_unknown_and_unavailable_are_explicit_without_invented_hash(section):
    record = CadSourceAssessment('large.svg', 'SVG', None, 'Unknown', 'unavailable', (), 'Source too large.')
    section.set_assessment(record)
    text = section.details.toPlainText().lower()
    assert 'unknown' in text and 'unavailable' in text and 'source too large' in text
    assert 'none recorded' in text


def owner(qtbot, payload=None):
    widget = QtWidgets.QWidget()
    qtbot.addWidget(widget)
    widget.custom_box = QtWidgets.QVBoxLayout(widget)
    return SimpleNamespace(ui=widget, cad_source=payload)


def test_attach_reuses_parent_owned_section_and_hides_absent(qtbot):
    obj = owner(qtbot, source_to_dict(assessment()))
    ui.attach_cad_source(obj)
    section = obj.ui.mikrocam_cad_source
    assert section.parent() is obj.ui and not section.isHidden()
    ui.attach_cad_source(obj)
    assert obj.ui.custom_box.count() == 1 and obj.ui.mikrocam_cad_source is section
    obj.cad_source = None
    ui.attach_cad_source(obj)
    assert section.isHidden() and section.details.toPlainText() == ''


def test_corrupt_other_owner_never_reuses_success(qtbot):
    first = owner(qtbot, source_to_dict(assessment('first.svg')))
    second = owner(qtbot, {'schema_version': 999})
    ui.attach_cad_source(first)
    ui.attach_cad_source(second)
    assert first.ui.mikrocam_cad_source is not second.ui.mikrocam_cad_source
    assert 'first.svg' in first.ui.mikrocam_cad_source.details.toPlainText()
    assert second.ui.mikrocam_cad_source.details.toPlainText() == ''
    assert not second.ui.mikrocam_cad_source.isHidden()


def test_semantically_invalid_payload_clears_previous_success(qtbot):
    obj = owner(qtbot, source_to_dict(assessment('before.svg')))
    ui.attach_cad_source(obj)
    obj.cad_source['evidence'][0]['value'] = 'Generated by Illustrator'
    ui.attach_cad_source(obj)
    section = obj.ui.mikrocam_cad_source
    assert not section.isHidden() and section.details.toPlainText() == ''
    assert 'unavailable' in section.summary_label.text().lower()
    assert 'before.svg' not in section.summary_label.text()


def test_parent_destruction_owns_section_lifetime(qtbot):
    obj = owner(qtbot, source_to_dict(assessment()))
    ui.attach_cad_source(obj)
    section = obj.ui.mikrocam_cad_source
    obj.ui.deleteLater()
    QtWidgets.QApplication.sendPostedEvents(None, QtCore.QEvent.Type.DeferredDelete)
    assert isdeleted(section)


def test_record_adapter_has_no_widget_access_even_in_background_thread(monkeypatch):
    calls = []
    monkeypatch.setattr(ui, 'store_cad_source', lambda *args: calls.append(args))
    class Host:
        def __getattr__(self, name):
            pytest.fail(f'Adapter accessed host/widget {name}')
    obj = Host()
    worker = threading.Thread(target=ui.record_cad_source,
                              args=(obj, '<svg/>', 'folder/' + 'a' * 300 + '.svg', 'SVG'))
    worker.start()
    worker.join(2)
    assert not worker.is_alive()
    assert calls == [(obj, '<svg/>', 'a' * 256, 'SVG')]
