import pytest

from mikrocam.importers.cad_dxf_source import dxf_source_evidence


def dxf(*pairs):
    return ''.join(f'{code}\r\n{value}\r\n' for code, value in pairs).encode('utf-8')


@pytest.mark.parametrize('declaration,application', [
    ('Generator: KiCad 10.0.6', 'KiCad'), ('Creator: PCBNEW', 'KiCad'),
    ('Created with Eeschema 9.0', 'KiCad'), ('Generated by Adobe Illustrator 29.0', 'Illustrator'),
    ('Creator: Illustrator', 'Illustrator'), ('Generated by Inkscape 1.1.1', 'Inkscape'),
    ('Generator: Labcenter Proteus 8.6', 'Proteus'), ('Created with Proteus', 'Proteus'),
    ('Creator: Unsupported CAD 5', 'Unknown'),
])
@pytest.mark.parametrize('scope', ['outside', 'header'])
def test_explicit_producer_comments_in_allowed_scope(declaration, application, scope):
    pairs = [(999, declaration)]
    if scope == 'header':
        pairs = [(0, 'SECTION'), (2, 'HEADER'), *pairs, (0, 'ENDSEC')]
    evidence = dxf_source_evidence(dxf(*pairs, (0, 'EOF')))
    assert len(evidence) == 1
    assert (evidence[0].application, evidence[0].field, evidence[0].value) == (
        application, 'dxf.999', declaration)


def test_original_comment_and_bom_are_retained_without_normalization():
    comment = '  Creator: Inkscape 1.1.1  '
    evidence = dxf_source_evidence(b'\xef\xbb\xbf' + dxf((999, comment), (0, 'EOF')))
    assert evidence[0].value == comment


def test_comments_in_entities_tables_and_blocks_are_not_producer_evidence():
    pairs = []
    for name in ('ENTITIES', 'TABLES', 'BLOCKS'):
        pairs.extend([(0, 'SECTION'), (2, name), (999, 'Generator: KiCad'),
                      (0, 'TEXT'), (1, 'Created with Inkscape'),
                      (2, 'KICAD'), (0, 'ENDSEC')])
    assert dxf_source_evidence(dxf(*pairs, (0, 'EOF'))) == ()


@pytest.mark.parametrize('comment', ['KiCad', 'Artwork created with Inkscape',
    'Not Generator: Proteus', 'Created on 2026-09-27', 'Image generated by PCBNEW'])
def test_unstructured_or_non_dxf_declaration_comments_are_not_guessed(comment):
    assert dxf_source_evidence(dxf((999, comment), (0, 'EOF'))) == ()


def test_header_variables_are_not_producer_fields():
    source = dxf((0, 'SECTION'), (2, 'HEADER'), (9, '$LASTSAVEDBY'), (1, 'Inkscape'),
                 (9, '$ACADVER'), (1, 'AC1018'), (9, '$INSUNITS'), (70, '4'),
                 (0, 'ENDSEC'), (0, 'EOF'))
    assert dxf_source_evidence(source) == ()


def test_repeated_identical_evidence_is_bounded_and_different_claims_are_preserved():
    comments = [(999, 'Generator: KiCad')] * 40 + [(999, 'Creator: Inkscape')]
    evidence = dxf_source_evidence(dxf(*comments, (0, 'EOF')))
    assert [e.application for e in evidence] == ['KiCad', 'Inkscape']


@pytest.mark.parametrize('pairs', [
    [(0, 'SECTION'), (2, 'HEADER')], [(0, 'ENDSEC'), (0, 'EOF')],
    [(0, 'SECTION'), (9, 'HEADER'), (0, 'ENDSEC'), (0, 'EOF')],
    [(0, 'SECTION'), (2, ''), (0, 'ENDSEC'), (0, 'EOF')],
    [(0, 'SECTION'), (2, 'HEADER'), (0, 'SECTION'), (2, 'TABLES'), (0, 'ENDSEC'), (0, 'EOF')],
    [(0, 'SECTION'), (2, 'HEADER'), (0, 'EOF')],
    [(0, 'EOF'), (999, 'Generator: KiCad')], [(0, 'EOF'), (0, 'EOF')],
    [(1, 'Generator: KiCad'), (0, 'EOF')], [(-1, 'comment'), (0, 'EOF')],
    [(1072, 'comment'), (0, 'EOF')], [('1.5', 'comment'), (0, 'EOF')],
    [('abc', 'comment'), (0, 'EOF')],
])
def test_malformed_complete_structure_never_returns_partial_positive(pairs):
    with pytest.raises(ValueError):
        dxf_source_evidence(dxf((999, 'Creator: KiCad'), *pairs))


@pytest.mark.parametrize('source', [b'', b'999\nGenerator: KiCad\n0',
    b'0\nEOF\n\n', b'AutoCAD Binary DXF\r\n\x1a\x00',
    b'999\nCreator: Inkscape\xff\n0\nEOF\n', '0\nEOF\n', b'0\x0bEOF\n'])
def test_invalid_pairs_encoding_binary_and_types_reject(source):
    with pytest.raises(ValueError):
        dxf_source_evidence(source)


def test_pair_cap_boundary_rejects_before_partial_identification(monkeypatch):
    from mikrocam.importers import cad_dxf_source as module
    monkeypatch.setattr(module, 'MAX_DXF_PAIRS', 2)
    assert dxf_source_evidence(dxf((999, 'Generator: KiCad'), (0, 'EOF')))[0].application == 'KiCad'
    with pytest.raises(ValueError, match='pair'):
        dxf_source_evidence(dxf((999, 'Generator: KiCad'), (999, 'plain'), (0, 'EOF')))


def test_line_cap_applies_to_ignored_values_and_code_lines():
    for source in (dxf((999, 'x' * 8193), (0, 'EOF')),
                   dxf(('0' * 8193, 'EOF'))):
        with pytest.raises(ValueError, match='line'):
            dxf_source_evidence(source)
    assert dxf_source_evidence(dxf((999, 'x' * 8192), (0, 'EOF'))) == ()


def test_evidence_overflow_and_long_marker_reject_without_truncating():
    with pytest.raises(ValueError):
        dxf_source_evidence(dxf(*[(999, f'Creator: KiCad {i}') for i in range(33)], (0, 'EOF')))
    with pytest.raises(ValueError):
        dxf_source_evidence(dxf((999, 'Creator: ' + 'x' * 512), (0, 'EOF')))


def test_shared_byte_cap_is_checked_before_decode(monkeypatch):
    from mikrocam.importers import cad_dxf_source as module
    source = dxf((0, 'EOF'))
    monkeypatch.setattr(module, 'MAX_CAD_SOURCE_BYTES', len(source))
    assert dxf_source_evidence(source) == ()
    monkeypatch.setattr(module, 'MAX_CAD_SOURCE_BYTES', len(source) - 1)
    with pytest.raises(ValueError, match='byte'):
        dxf_source_evidence(source)


def test_group_code_range_is_checked_inside_otherwise_valid_header():
    for code in ('-1', '1072', '999.0', '٩٩٩'):
        with pytest.raises(ValueError, match='code'):
            dxf_source_evidence(dxf((0, 'SECTION'), (2, 'HEADER'), (code, 'ignored'),
                                    (0, 'ENDSEC'), (0, 'EOF')))
    assert dxf_source_evidence(dxf((0, 'SECTION'), (2, 'HEADER'), (1071, 'ignored'),
                                  (0, 'ENDSEC'), (0, 'EOF'))) == ()


def test_maximum_code_line_and_ordinary_lf_cr_endings_are_supported():
    assert dxf_source_evidence(dxf(('0' * 8192, 'EOF'))) == ()
    for ending in (b'\n', b'\r'):
        source = dxf((999, 'Creator: KiCad'), (0, 'EOF')).replace(b'\r\n', ending)
        assert dxf_source_evidence(source)[0].application == 'KiCad'
