"""Atomic retained metadata publication without source, geometry or settings mutation."""
from copy import deepcopy
from hashlib import sha256
from types import SimpleNamespace

import pytest

import mikrocam.bridge.cad_source as bridge
from mikrocam.core.cad_source import CadSourceAssessment, CadSourceEvidence
from mikrocam.core.cad_source_codec import source_to_dict


def detected(source, name, source_format):
    return CadSourceAssessment(name, source_format, sha256(source).hexdigest(), 'KiCad', 'identified',
                               (CadSourceEvidence('KiCad', 'svg.desc', 'Generated by KiCad'),), 'Explicit claim.')


def test_store_hashes_exact_utf8_bom_and_newlines_without_mutating_host(monkeypatch):
    calls = []
    def inspect(source, name, source_format):
        calls.append((source, name, source_format))
        return detected(source, name, source_format)
    monkeypatch.setattr(bridge, 'detect_cad_source', inspect)
    source = '\ufeff<svg>Üretim\r\n</svg>\n'
    owner = SimpleNamespace(source_file=source, solid_geometry=['sentinel'], tools={'a': {'feedrate': 321}})
    before = deepcopy(vars(owner))
    bridge.store_cad_source(owner, source, 'exact.svg', 'SVG')
    assert calls == [(source.encode('utf-8'), 'exact.svg', 'SVG')]
    record = bridge.read_cad_source(owner)
    assert record.source_sha256 == sha256(source.encode('utf-8')).hexdigest()
    assert {key: value for key, value in vars(owner).items() if key != 'cad_source'} == before


@pytest.mark.parametrize('text', ['x' * 11, 'é' * 6, '🙂' * 3])
def test_oversized_text_never_calls_detector_and_publishes_unavailable(monkeypatch, text):
    monkeypatch.setattr(bridge, 'MAX_CAD_SOURCE_BYTES', 10)
    monkeypatch.setattr(bridge, 'detect_cad_source', lambda *args: pytest.fail('Oversized source reached detector'))
    owner = SimpleNamespace(cad_source={'old': True})
    bridge.store_cad_source(owner, text, 'large.svg', 'SVG')
    record = bridge.read_cad_source(owner)
    assert record.application == 'Unknown' and record.status == 'unavailable'
    assert record.source_sha256 is None and record.evidence == ()


def test_exact_multibyte_source_byte_cap_is_accepted(monkeypatch):
    monkeypatch.setattr(bridge, 'MAX_CAD_SOURCE_BYTES', 10)
    monkeypatch.setattr(bridge, 'detect_cad_source', detected)
    owner = SimpleNamespace()
    bridge.store_cad_source(owner, 'é' * 5, 'boundary.svg', 'SVG')
    assert bridge.read_cad_source(owner).source_sha256 == sha256(('é' * 5).encode()).hexdigest()


def test_unencodable_source_is_unavailable_without_partial_evidence(monkeypatch):
    monkeypatch.setattr(bridge, 'detect_cad_source', lambda *args: pytest.fail('Invalid UTF8 reached detector'))
    owner = SimpleNamespace()
    bridge.store_cad_source(owner, '<svg>\ud800</svg>', 'encoding.svg', 'SVG')
    record = bridge.read_cad_source(owner)
    assert record.status == 'unavailable' and record.source_sha256 is None and record.evidence == ()


def test_over_budget_evidence_falls_back_to_unavailable_but_retains_source_hash(monkeypatch):
    def excessive(source, name, source_format):
        claims = tuple(CadSourceEvidence('Unknown', 'svg.xmp.CreatorTool',
                                        '🙂' * (512 - len(str(i))) + str(i)) for i in range(32))
        return CadSourceAssessment(name, source_format, sha256(source).hexdigest(), 'Unknown',
                                   'unknown', claims, 'Explicit unsupported declarations.')
    monkeypatch.setattr(bridge, 'detect_cad_source', excessive)
    owner = SimpleNamespace()
    bridge.store_cad_source(owner, '<svg/>', 'evidence.svg', 'SVG')
    record = bridge.read_cad_source(owner)
    assert record.status == 'unavailable' and record.evidence == ()
    assert record.source_sha256 == sha256(b'<svg/>').hexdigest()


@pytest.mark.parametrize('failing_stage', ['detect_cad_source', 'source_to_dict'])
def test_unexpected_failure_preserves_previous_payload(monkeypatch, failing_stage):
    monkeypatch.setattr(bridge, 'detect_cad_source', detected)
    def fail(*args):
        raise RuntimeError('Injected unexpected failure')
    monkeypatch.setattr(bridge, failing_stage, fail)
    old = {'previous': 'historical'}
    owner = SimpleNamespace(cad_source=old)
    with pytest.raises(RuntimeError):
        bridge.store_cad_source(owner, '<svg/>', 'new.svg', 'SVG')
    assert owner.cad_source is old


@pytest.mark.parametrize('args', [(b'<svg/>', 'x.svg', 'SVG'), ('<svg/>', '', 'SVG'),
                                  ('<svg/>', 'x.svg', 'svg'), ('<svg/>', 'x.svg', 'PDF')])
def test_caller_errors_do_not_replace_previous_data(args):
    owner = SimpleNamespace(cad_source={'previous': True})
    with pytest.raises(ValueError):
        bridge.store_cad_source(owner, *args)
    assert owner.cad_source == {'previous': True}


def test_old_absence_and_read_do_not_reparse_or_access_host_geometry(monkeypatch):
    monkeypatch.setattr(bridge, 'detect_cad_source', lambda *args: pytest.fail('Read reparsed source'))
    class OldOwner:
        def __getattr__(self, name):
            if name == 'cad_source':
                raise AttributeError(name)
            pytest.fail(f'Unexpected host read: {name}')
    assert bridge.read_cad_source(OldOwner()) is None
    assert bridge.read_cad_source(SimpleNamespace(cad_source=None)) is None
    record = detected(b'<svg/>', 'old.svg', 'SVG')
    owner = SimpleNamespace(cad_source=source_to_dict(record))
    assert bridge.read_cad_source(owner) == record
    owner.cad_source = {'schema_version': 999}
    with pytest.raises(ValueError):
        bridge.read_cad_source(owner)


def test_stored_claim_semantics_cannot_conflict_with_record_application():
    mismatched = CadSourceAssessment('mismatch.dxf', 'DXF', 'a' * 64, 'Illustrator', 'identified',
                                     (CadSourceEvidence('Illustrator', 'dxf.999', 'Creator: KiCad'),),
                                     'Persisted claim is inconsistent.')
    owner = SimpleNamespace(cad_source=source_to_dict(mismatched))
    with pytest.raises(ValueError):
        bridge.read_cad_source(owner)


def test_detected_invalid_claim_semantics_become_unavailable_not_partial_positive(monkeypatch):
    def mismatch(source, name, source_format):
        return CadSourceAssessment(name, source_format, sha256(source).hexdigest(), 'Illustrator', 'identified',
                                   (CadSourceEvidence('Illustrator', 'svg.desc', 'Generated by KiCad'),), 'Bad claim.')
    monkeypatch.setattr(bridge, 'detect_cad_source', mismatch)
    owner = SimpleNamespace()
    bridge.store_cad_source(owner, '<svg/>', 'mismatch.svg', 'SVG')
    assert bridge.read_cad_source(owner).status == 'unavailable'
