"""Offline allowlist for the standard SVG 1.0/1.1 public DOCTYPE (spec 041, US1)."""
import socket
import urllib.request

import pytest
from shapely import union_all

from mikrocam.bridge.svg_import import import_svg_bytes
from mikrocam.importers.cad_svg_source import svg_source_evidence
from mikrocam.importers.svg_document import parse_svg_document
from mikrocam.importers.svg_doctype import SVG_PUBLIC_DOCTYPES, strip_svg_doctype

SVG11 = ('<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" '
         '"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">')
SVG10 = ('<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN"\n'
         '\t"http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">')
BODY = ('<svg xmlns="http://www.w3.org/2000/svg" width="20mm" height="10mm" viewBox="0 0 20 10">'
        '<desc>Image generated by PCBNEW</desc>'
        '<rect x="1" y="2" width="5" height="3"/><circle cx="12" cy="5" r="2" fill="red"/></svg>')
DECLARATION = '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\r\n'
GENERATOR = '<!-- Generator: Adobe Illustrator 16.0.0, SVG Export Plug-In . SVG Version: 6.00 -->\n'


def test_allowlist_is_exactly_the_w3c_svg10_and_svg11_identifiers():
    assert SVG_PUBLIC_DOCTYPES == (
        ('-//W3C//DTD SVG 1.0//EN', 'http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd'),
        ('-//W3C//DTD SVG 1.1//EN', 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'))


@pytest.mark.parametrize('prolog', [
    SVG11, SVG10, DECLARATION + SVG11, DECLARATION + GENERATOR + SVG11 + '\n',
    '\ufeff' + DECLARATION + '<?pi data?>\n<!-- a - b -->' + SVG10,
    SVG11.replace('"', "'"), SVG11.replace(' PUBLIC ', '\r\n  PUBLIC\t').replace('">', '"  >')])
@pytest.mark.parametrize('object_type', ['geometry', 'gerber'])
@pytest.mark.parametrize('flip', [False, True])
def test_standard_doctype_imports_exactly_like_the_same_source_without_it(prolog, object_type, flip):
    plain = DECLARATION + BODY if prolog.lstrip('\ufeff').startswith(DECLARATION) else BODY
    expected = import_svg_bytes(plain.encode(), 'a.svg', flip=flip, object_type=object_type)
    actual = import_svg_bytes((prolog + BODY).encode(), 'a.svg', flip=flip, object_type=object_type)
    assert union_all(actual.geometry_mm).equals_exact(union_all(expected.geometry_mm), 0)
    assert len(actual.document.elements) == 2
    assert actual.document.viewport == expected.document.viewport


def test_blanking_keeps_offsets_and_line_numbers_for_later_errors():
    text = DECLARATION + SVG10 + '\n<svg/>'
    stripped = strip_svg_doctype(text)
    assert len(stripped) == len(text) and stripped.count('\n') == text.count('\n')
    assert '<!DOCTYPE' not in stripped and stripped.endswith('<svg/>')
    assert strip_svg_doctype(BODY) == BODY


def test_standard_doctype_never_opens_a_network_connection(monkeypatch):
    def forbidden(*args, **kwargs):
        raise AssertionError('network access attempted')
    monkeypatch.setattr(socket, 'socket', forbidden)
    monkeypatch.setattr(socket, 'create_connection', forbidden)
    monkeypatch.setattr(urllib.request, 'urlopen', forbidden)
    assert import_svg_bytes((SVG11 + BODY).encode(), 'a.svg').geometry_mm
    assert svg_source_evidence((SVG10 + BODY).encode())[0].application == 'KiCad'


ADVERSARIAL = {
    'empty internal subset': (SVG11[:-1] + ' []>' + BODY, 'internal subset'),
    'internal entity': ('<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" '
                        '"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" '
                        '[<!ENTITY ns_svg "http://www.w3.org/2000/svg">]>'
                        + BODY.replace('"http://www.w3.org/2000/svg"', '"&ns_svg;"'), 'internal subset'),
    'subset only': ('<!DOCTYPE svg [<!ENTITY x "1">]>' + BODY, 'internal subset'),
    'parameter entity': ('<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" '
                         '"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" '
                         '[<!ENTITY % remote SYSTEM "http://example.invalid/x.dtd"> %remote;]>' + BODY,
                         'internal subset'),
    'billion laughs': ('<!DOCTYPE svg [<!ENTITY a "aaaa"><!ENTITY b "&a;&a;&a;&a;">'
                       '<!ENTITY c "&b;&b;&b;&b;">]>' + BODY.replace('PCBNEW', '&c;'), 'internal subset'),
    'system only': ('<!DOCTYPE svg SYSTEM "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">' + BODY,
                    'standard SVG 1.0/1.1 public'),
    'bare name': ('<!DOCTYPE svg>' + BODY, 'standard SVG 1.0/1.1 public'),
    'unknown public': (SVG11.replace('SVG 1.1//EN', 'SVG 1.1 Tiny//EN') + BODY, 'unknown SVG DOCTYPE'),
    'unknown system': (SVG11.replace('http://www.w3.org/', 'https://example.invalid/') + BODY,
                       'unknown SVG DOCTYPE'),
    'mismatched pair': (SVG11.replace('SVG 1.1//EN', 'SVG 1.0//EN') + BODY, 'unknown SVG DOCTYPE'),
    'html root name': (SVG11.replace('DOCTYPE svg', 'DOCTYPE html') + BODY, 'standard SVG 1.0/1.1 public'),
    'lowercase keyword': (SVG11.replace('DOCTYPE', 'doctype') + BODY, 'declarations are unsupported'),
    'after root': (BODY.replace('<desc>', SVG11 + '<desc>'), 'declarations are unsupported'),
    'second doctype': (SVG11 + SVG11 + BODY, 'declarations are unsupported'),
    'entity outside doctype': (SVG11 + BODY.replace('<desc>', '<!ENTITY x "1"><desc>'),
                               'declarations are unsupported'),
    'undefined reference': (SVG11 + BODY.replace('PCBNEW', '&ns_svg;'), 'undefined entity'),
}


@pytest.mark.parametrize('name', sorted(ADVERSARIAL))
def test_adversarial_dtd_is_rejected_by_the_geometry_importer(name):
    text, message = ADVERSARIAL[name]
    with pytest.raises(ValueError, match=message):
        parse_svg_document(text.encode(), 'evil.svg')


@pytest.mark.parametrize('name', sorted(set(ADVERSARIAL) - {'undefined reference'}))
def test_adversarial_dtd_is_rejected_by_the_source_detector(name):
    with pytest.raises(ValueError, match=ADVERSARIAL[name][1]):
        svg_source_evidence(ADVERSARIAL[name][0].encode())


def test_detector_and_importer_share_the_same_rejection_for_undefined_entities():
    with pytest.raises(ValueError):
        svg_source_evidence(ADVERSARIAL['undefined reference'][0].encode())
