"""Strict immutable historical producer claims, without geometry or desktop dependencies."""
from dataclasses import FrozenInstanceError, replace

import pytest

from mikrocam.core.cad_source import CAD_APPLICATIONS, CadSourceAssessment, CadSourceEvidence


def evidence(application='KiCad', field='svg.desc', value='Generated by KiCad 9.0'):
    return CadSourceEvidence(application, field, value)


def assessment(**changes):
    values = dict(source_name='copper.svg', source_format='SVG', source_sha256='a' * 64,
                  application='KiCad', status='identified', evidence=(evidence(),),
                  reason='Explicit generator declaration.')
    values.update(changes)
    return CadSourceAssessment(**values)


def test_known_application_identity_and_frozen_records():
    assert set(CAD_APPLICATIONS) == {'KiCad', 'Illustrator', 'Inkscape', 'Proteus', 'Unknown'}
    assert type(CAD_APPLICATIONS) is tuple
    record = assessment()
    with pytest.raises(FrozenInstanceError):
        record.application = 'Unknown'
    with pytest.raises(FrozenInstanceError):
        record.evidence[0].value = 'replacement'


@pytest.mark.parametrize('application', ['KiCad', 'Illustrator', 'Inkscape', 'Proteus'])
def test_identification_requires_that_exact_positive_application(application):
    record = assessment(application=application, evidence=(evidence(application),))
    assert record.application == record.evidence[0].application


@pytest.mark.parametrize(('status', 'records'), [
    ('unknown', ()), ('unknown', (evidence('Unknown'),)),
    ('conflicting', (evidence('KiCad'), evidence('Illustrator'))),
    ('conflicting', (evidence('KiCad'), evidence('Unknown'))), ('unavailable', ()),
])
def test_uncertain_status_is_explicitly_unknown(status, records):
    assert assessment(application='Unknown', status=status, evidence=records).status == status


def test_unavailable_can_retain_exact_input_hash_or_have_no_hash():
    for digest in ('b' * 64, None):
        assert assessment(application='Unknown', status='unavailable', evidence=(),
                          source_sha256=digest).source_sha256 == digest


def test_utf8_character_bounds_are_inclusive_and_preserve_exact_tokens():
    claim = evidence(field='é' * 80, value='🙂' * 512)
    record = assessment(source_name='é' * 256, reason='🙂' * 512, evidence=(claim,))
    assert record.evidence[0].value == '🙂' * 512
    assert assessment(source_format='DXF').source_format == 'DXF'


@pytest.mark.parametrize('kwargs', [
    {'application': 'kicad'}, {'application': None}, {'field': ''}, {'field': 'f' * 81},
    {'field': 1}, {'field': '\ud800'}, {'value': ''}, {'value': 'x' * 513},
    {'value': []}, {'value': '\udfff'},
])
def test_evidence_rejects_unknown_types_bounds_and_invalid_unicode(kwargs):
    with pytest.raises(ValueError):
        evidence(**kwargs)


@pytest.mark.parametrize('changes', [
    {'source_name': ''}, {'source_name': 'x' * 257}, {'source_name': '\ud800'},
    {'source_name': 7}, {'source_format': 'svg'}, {'source_format': 'PDF'},
    {'source_sha256': None}, {'source_sha256': 'A' * 64}, {'source_sha256': 'g' * 64},
    {'source_sha256': 'a' * 63}, {'source_sha256': 1}, {'reason': ''},
    {'reason': 'r' * 513}, {'reason': '\udfff'}, {'reason': False},
    {'application': 'Other'}, {'status': 'certain'}, {'status': None},
    {'evidence': []}, {'evidence': (object(),)}, {'evidence': (evidence(),) * 33},
    {'evidence': ()}, {'application': 'Unknown'}, {'evidence': (evidence('Inkscape'),)},
    {'evidence': (evidence(), evidence('Unknown'))}, {'evidence': (evidence(), evidence())},
])
def test_assessment_rejects_invalid_fields_and_identification(changes):
    with pytest.raises(ValueError):
        assessment(**changes)


@pytest.mark.parametrize(('status', 'records'), [
    ('unknown', (evidence(),)), ('conflicting', ()), ('conflicting', (evidence(),)),
    ('conflicting', (evidence(), evidence(field='svg.xmp.CreatorTool'))),
    ('unavailable', (evidence('Unknown'),)), ('unavailable', (evidence(),)),
])
def test_status_evidence_invariants(status, records):
    with pytest.raises(ValueError):
        assessment(status=status, application='Unknown', evidence=records)


@pytest.mark.parametrize('status', ['unknown', 'conflicting', 'unavailable'])
def test_nonidentified_assessment_cannot_name_positive_application(status):
    with pytest.raises(ValueError):
        assessment(status=status, application='KiCad', evidence=())


def test_exact_32_distinct_evidence_records_and_encounter_order():
    records = tuple(evidence(field=f'claim-{i}') for i in range(32))
    assert assessment(evidence=records).evidence == records
    with pytest.raises(ValueError):
        replace(assessment(evidence=records), evidence=records + (evidence(field='claim-33'),))
