"""Detached strict schema-one dictionaries with a canonical UTF-8 byte ceiling."""
from copy import deepcopy
import json

import pytest

from mikrocam.core.cad_source import CadSourceAssessment, CadSourceEvidence
from mikrocam.core.cad_source_codec import (
    MAX_SOURCE_REPORT_BYTES, SOURCE_SCHEMA_VERSION, source_from_dict, source_to_dict,
)


def record(status='identified'):
    return CadSourceAssessment('Üretim.svg', 'SVG', '1' * 64, 'KiCad' if status == 'identified' else 'Unknown',
                               status, (CadSourceEvidence('KiCad', 'svg.desc', 'Generated by KiCad 9'),)
                               if status == 'identified' else (), 'Historical producer evidence.')


def test_exact_schema_roundtrip_with_fresh_detached_containers():
    assert SOURCE_SCHEMA_VERSION == 1 and MAX_SOURCE_REPORT_BYTES == 65536
    original = record()
    first, second = source_to_dict(original), source_to_dict(original)
    assert set(first) == {'schema_version', 'source_name', 'source_format', 'source_sha256',
                         'application', 'status', 'evidence', 'reason'}
    assert first['evidence'] == [{'application': 'KiCad', 'field': 'svg.desc', 'value': 'Generated by KiCad 9'}]
    wire = json.loads(json.dumps(first, ensure_ascii=False))
    assert source_from_dict(wire) == original
    first['evidence'][0]['value'] = 'modified'
    assert second['evidence'][0]['value'] == original.evidence[0].value
    assert original.evidence[0].value == 'Generated by KiCad 9'


def test_decoding_does_not_mutate_input_or_retain_mutable_containers():
    data = source_to_dict(record())
    before = deepcopy(data)
    decoded = source_from_dict(data)
    assert data == before
    data['evidence'].clear()
    assert len(decoded.evidence) == 1


@pytest.mark.parametrize('status', ['unknown', 'unavailable'])
def test_uncertain_records_roundtrip_without_invented_evidence(status):
    original = record(status)
    assert source_from_dict(source_to_dict(original)) == original


def test_conflicting_known_and_unknown_claims_preserve_encounter_order():
    claims = (CadSourceEvidence('Unknown', 'svg.xmp.CreatorTool', 'Unrecognized CAD'),
              CadSourceEvidence('KiCad', 'svg.desc', 'Generated by KiCad'))
    original = CadSourceAssessment('conflict.dxf', 'DXF', '3' * 64, 'Unknown', 'conflicting',
                                   claims, 'Declarations disagree.')
    assert source_from_dict(source_to_dict(original)).evidence == claims


def test_unavailable_without_hash_roundtrips_as_explicit_null():
    original = CadSourceAssessment('large.svg', 'SVG', None, 'Unknown', 'unavailable', (), 'Source exceeds cap.')
    data = source_to_dict(original)
    assert data['source_sha256'] is None
    assert source_from_dict(data) == original


@pytest.mark.parametrize('value', [None, [], (), 1, 'report'])
def test_codec_none_is_not_old_owner_migration(value):
    with pytest.raises(ValueError):
        source_from_dict(value)
    with pytest.raises(ValueError):
        source_to_dict(value)


@pytest.mark.parametrize(('key', 'value'), [
    ('schema_version', True), ('schema_version', 1.0), ('schema_version', 0), ('schema_version', 2),
    ('schema_version', '1'), ('evidence', ()), ('evidence', {}), ('source_name', 2),
    ('source_sha256', None), ('source_format', 'svg'), ('status', 'bad'), ('reason', ''),
])
def test_wrong_schema_or_field_types_are_rejected(key, value):
    data = source_to_dict(record())
    data[key] = value
    with pytest.raises(ValueError):
        source_from_dict(data)


def test_unknown_and_missing_keys_rejected_at_both_record_levels():
    for nested in (False, True):
        data = source_to_dict(record())
        target = data['evidence'][0] if nested else data
        target['extra'] = 'x'
        with pytest.raises(ValueError):
            source_from_dict(data)
        del target['extra']
        del target['field' if nested else 'reason']
        with pytest.raises(ValueError):
            source_from_dict(data)


def test_duplicate_and_excessive_evidence_are_not_silently_truncated():
    data = source_to_dict(record())
    data['evidence'] *= 2
    with pytest.raises(ValueError):
        source_from_dict(data)
    data['evidence'] *= 17
    with pytest.raises(ValueError):
        source_from_dict(data)


def test_actual_multibyte_canonical_payload_exceeds_byte_budget():
    evidence = tuple(CadSourceEvidence('KiCad', f'field-{i}', '🙂' * 512) for i in range(32))
    original = CadSourceAssessment('large.svg', 'SVG', '2' * 64, 'KiCad', 'identified', evidence, 'Explicit claim.')
    with pytest.raises(ValueError, match='byte|limit'):
        source_to_dict(original)
    data = source_to_dict(record())
    data['evidence'] = [dict(application=e.application, field=e.field, value=e.value) for e in evidence]
    with pytest.raises(ValueError, match='byte|limit'):
        source_from_dict(data)


def test_exact_canonical_size_is_inclusive_and_applies_to_both_directions(monkeypatch):
    import mikrocam.core.cad_source_codec as codec
    data = source_to_dict(record())
    size = len(json.dumps(data, ensure_ascii=False, separators=(',', ':'), allow_nan=False).encode('utf-8'))
    monkeypatch.setattr(codec, 'MAX_SOURCE_REPORT_BYTES', size)
    assert source_from_dict(data) == record()
    assert source_to_dict(record()) == data
    monkeypatch.setattr(codec, 'MAX_SOURCE_REPORT_BYTES', size - 1)
    with pytest.raises(ValueError, match='byte|limit'):
        source_from_dict(data)
    with pytest.raises(ValueError, match='byte|limit'):
        source_to_dict(record())
