"""Only finite producer claims in their declared SVG metadata context qualify."""
import pytest

from mikrocam.importers.cad_svg_source import svg_source_evidence


def source(body='', attrs=''):
    return f'<svg xmlns="http://www.w3.org/2000/svg" {attrs}>{body}</svg>'.encode()


def test_root_inkscape_version_uses_expanded_namespace_not_prefix():
    evidence = svg_source_evidence(source(attrs='xmlns:i="http://www.inkscape.org/namespaces/inkscape" '
                                         'i:version="1.1.1 (abcdef)"'))
    assert len(evidence) == 1 and evidence[0].application == 'Inkscape'
    assert evidence[0].field == 'svg.inkscape.version' and evidence[0].value == '1.1.1 (abcdef)'


@pytest.mark.parametrize('field', ['<r:Description x:CreatorTool="Adobe Illustrator 28"/>',
                                  '<r:Description><x:CreatorTool>Adobe Illustrator 28</x:CreatorTool></r:Description>'])
def test_creator_tool_element_or_attribute_only_under_root_metadata(field):
    payload = source('<metadata><r:RDF>' + field + '</r:RDF></metadata>',
                     'xmlns:x="http://ns.adobe.com/xap/1.0/" xmlns:r="urn:rdf"')
    evidence = svg_source_evidence(payload)
    assert len(evidence) == 1 and evidence[0].application == 'Illustrator'
    assert evidence[0].field == 'svg.xmp.CreatorTool' and evidence[0].value == 'Adobe Illustrator 28'


@pytest.mark.parametrize('body', [
    '<desc>KiCad board</desc>', '<text>Generator: KiCad</text>', '<title>Generated by KiCad</title>',
    '<g><desc>Image generated by PCBNEW</desc><!--Generator: KiCad--></g>',
    '<metadata><!--Generator: KiCad--></metadata>',
    '<g xmlns:i="http://www.inkscape.org/namespaces/inkscape" i:version="1.2"/>',
    '<g xmlns:x="http://ns.adobe.com/xap/1.0/"><x:CreatorTool>KiCad</x:CreatorTool></g>',
    '<f:metadata xmlns:f="urn:foreign" xmlns:x="http://ns.adobe.com/xap/1.0/" x:CreatorTool="KiCad"/>',
    '<metadata xmlns:x="urn:fake"><x:CreatorTool>KiCad</x:CreatorTool></metadata>',
    '<metadata xmlns:f="urn:foreign" xmlns:x="http://ns.adobe.com/xap/1.0/">'
    '<f:metadata><x:CreatorTool>Adobe Illustrator 28</x:CreatorTool></f:metadata></metadata>',
    '<metadata xmlns:t="http://ns.adobe.com/xap/1.0/t/pg/" xmlns:d="http://ns.adobe.com/xap/1.0/sType/Dimensions#">'
    '<t:MaxPageSize d:w="10" d:h="10" d:unit="mm"/></metadata>',
])
def test_misleading_drawing_or_foreign_metadata_does_not_identify_source(body):
    assert svg_source_evidence(source(body)) == ()


def test_direct_desc_and_document_generator_comments_retain_original_values():
    payload = (b'<!-- Generator: Adobe Illustrator 25.0, SVG Export Plug-In . SVG Version: 6.00 -->'
               + source('<desc>Image generated by PCBNEW </desc><!--Created with Inkscape 1.2-->'))
    evidence = svg_source_evidence(payload)
    assert [e.application for e in evidence] == ['Illustrator', 'KiCad', 'Inkscape']
    assert evidence[0].value.startswith(' Generator:')


def test_fixed_external_svg11_doctype_is_inspected_offline():
    payload = (b'<?xml version="1.0"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" '
               b'"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">'
               + source('<desc>Image generated by PCBNEW</desc>'))
    assert svg_source_evidence(payload)[0].application == 'KiCad'


@pytest.mark.parametrize('payload', [b'<svg', b'<html/>', b'\xff',
    b'<!DOCTYPE svg SYSTEM "https://example.invalid/a.dtd"><svg/>',
    b'<!DOCTYPE svg [<!ENTITY tool "KiCad">]><svg><desc>&tool;</desc></svg>',
    b'<svg xmlns:i="http://www.inkscape.org/namespaces/inkscape" i:version="bogus"/>'])
def test_malformed_or_unsupported_metadata_is_explicit(payload):
    with pytest.raises(ValueError):
        svg_source_evidence(payload)


def test_tree_and_evidence_limits_are_checked(monkeypatch):
    from mikrocam.importers import cad_svg_source as parser
    monkeypatch.setattr(parser, 'MAX_XML_DEPTH', 3)
    with pytest.raises(ValueError, match='limit|budget'):
        svg_source_evidence(source('<g><g><g/></g></g>'))
    monkeypatch.setattr(parser, 'MAX_XML_ELEMENTS', 2)
    with pytest.raises(ValueError, match='limit|budget'):
        svg_source_evidence(source('<g/><g/>'))


def test_known_doctype_cannot_make_invalid_document_structure_valid():
    declaration = ('<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" '
                   '"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">')
    with pytest.raises(ValueError):
        svg_source_evidence(source(declaration + '<desc>Generated by KiCad</desc>'))


def test_many_comments_and_excess_evidence_never_produce_partial_identification():
    from mikrocam.importers.cad_source import detect_cad_source
    payload = source(''.join(f'<desc>Generated by KiCad {index}</desc>' for index in range(33)))
    record = detect_cad_source(payload, 'x.svg', 'SVG')
    assert record.application == 'Unknown' and record.status == 'unavailable'
    assert record.evidence == ()


def test_duplicate_claims_are_canonical_without_spending_evidence_budget():
    from mikrocam.importers.cad_source import detect_cad_source
    payload = source('<desc>Generated by KiCad 10</desc>' * 40)
    record = detect_cad_source(payload, 'x.svg', 'SVG')
    assert record.application == 'KiCad' and len(record.evidence) == 1
